pod:
  name: my-pod
container:
  name: my-container
  image: nginx
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
serviceAccount:
  create: true
  # ... cualquier otro valor relacionado con serviceAccount
customLabel: "app={{ .Chart.Name }}"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  # ... otras configuraciones para autoscaling ...

ingress:
  enabled: true
  defaultBackend:
    service:
      name: my-app-service
      port:
        number: 80
  rules:
    - host: my-app.example.com
      http:
        paths:
        - backend:
            service:
              name: my-app-service
              port:
                number: 80
          path: /
          pathType: ImplementationSpecific

service:
  port: 80
image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent
